// Options exposed to normal Nextcloud users.
// Keep this list in sync with lib/Db/Settings.php.
const safeYtdlOptions = [
  "ignore-errors", "no-abort-on-error", "abort-on-error",
  "flat-playlist", "no-flat-playlist", "live-from-start", "no-live-from-start",
  "wait-for-video", "no-wait-for-video", "no-colors", "socket-timeout",
  "force-ipv4", "force-ipv6", "playlist-start", "playlist-end", "playlist-items",
  "min-filesize", "max-filesize", "date", "datebefore", "dateafter",
  "match-filters", "no-match-filter", "no-playlist", "yes-playlist", "age-limit",
  "max-downloads", "break-on-existing", "break-on-reject", "break-per-input",
  "no-break-per-input", "skip-playlist-after-errors", "concurrent-fragments",
  "limit-rate", "throttled-rate", "retries", "file-access-retries",
  "fragment-retries", "skip-unavailable-fragments", "abort-on-unavailable-fragment",
  "keep-fragments", "no-keep-fragments", "buffer-size", "resize-buffer",
  "no-resize-buffer", "http-chunk-size", "playlist-reverse", "no-playlist-reverse",
  "playlist-random", "output", "output-na-placeholder", "restrict-filenames",
  "no-restrict-filenames", "windows-filenames", "no-windows-filenames",
  "trim-filenames", "no-overwrites", "force-overwrites", "no-force-overwrites",
  "continue", "no-continue", "part", "no-part", "mtime", "no-mtime",
  "write-description", "no-write-description", "write-info-json", "no-write-info-json",
  "write-playlist-metafiles", "no-write-playlist-metafiles", "clean-info-json",
  "no-clean-info-json", "write-comments", "no-write-comments", "write-thumbnail",
  "no-write-thumbnail", "write-all-thumbnails", "list-thumbnails", "no-simulate",
  "skip-download", "dump-json", "dump-single-json", "newline", "no-progress",
  "progress", "progress-template", "verbose", "encoding", "sleep-requests",
  "sleep-interval", "max-sleep-interval", "sleep-subtitles", "format", "format-sort",
  "format-sort-force", "no-format-sort-force", "video-multistreams",
  "no-video-multistreams", "audio-multistreams", "no-audio-multistreams",
  "prefer-free-formats", "no-prefer-free-formats", "check-formats",
  "check-all-formats", "no-check-formats", "list-formats", "merge-output-format",
  "write-subs", "no-write-subs", "write-auto-subs", "no-write-auto-subs",
  "list-subs", "sub-format", "sub-langs", "extract-audio", "audio-format",
  "audio-quality", "remux-video", "recode-video", "keep-video", "no-keep-video",
  "post-overwrites", "no-post-overwrites", "embed-subs", "no-embed-subs",
  "embed-thumbnail", "no-embed-thumbnail", "embed-metadata", "no-embed-metadata",
  "embed-chapters", "no-embed-chapters", "embed-info-json", "no-embed-info-json",
  "parse-metadata", "replace-in-metadata", "concat-playlist", "fixup",
  "convert-subs", "convert-thumbnails", "split-chapters", "no-split-chapters",
  "remove-chapters", "no-remove-chapters", "force-keyframes-at-cuts",
  "no-force-keyframes-at-cuts", "sponsorblock-mark", "sponsorblock-remove",
  "sponsorblock-chapter-title", "no-sponsorblock", "extractor-retries",
  "allow-dynamic-mpd", "ignore-dynamic-mpd", "hls-split-discontinuity",
  "no-hls-split-discontinuity", "extractor-args"
];

export default safeYtdlOptions;
